# Generated by Django 5.2.13 on 2026-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadline',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
